name: "GraalVM Testing"
description: "Perform GraalVM testing with the given build script."
inputs:
  build_script:
    description: "Relative path to the build script to be used."
runs:
  using: 'composite'
  steps:
    - name: GraalVM 22.3.2 + Java 17
      uses: docker://gcr.io/cloud-devrel-kokoro-resources/graalvm17:22.3.2
      with:
        entrypoint: /bin/echo
        args: "GraalVM 22.3.2 + Java 17"

    - name: GraalVM 22.3.2 + Java 11
      uses: docker://gcr.io/cloud-devrel-kokoro-resources/graalvm:22.3.2
      with:
        entrypoint: /bin/echo
        args: "GraalVM 22.3.2 + Java 11"
